#pragma kernel CSMain

#define GROUP_SIZE 8
#define BVH_STACK_SIZE 32

float3 SDFLower; //AABB 最小值
int TriangleCount; 

float3 SDFUpper; //AABB 最大值
int SignRayCount;

float3 SDFExtent;//AABB Size
int XBeg; //体素 X开始值 =》0

int XEnd;//体素 X结束值=>resolution
 
struct Node
{
    float minX;
    float minY;
    float minZ;
    float maxX;
    float maxY;
    float maxZ;
    uint childIndex;
    uint childCount;
};

StructuredBuffer<Node> Nodes;//bvh node
StructuredBuffer<float3> Vertices;
StructuredBuffer<float3> Normals;

RWTexture3D<float> SDF;

float dot2(float3 v)
{
    return dot(v, v);
}

bool isLeaf(Node node)
{
    return node.childCount != 0;
}
///球体和 AABB包围盒相交检测
///p  球体中心点  radius2  球体半径平方
///lower  aabb最小   upper aabb最大
bool intersectSphereBox(float3 lower, float3 upper, float3 p, float radius2)
{
    float3 q = clamp(p, lower, upper);// 把球心p钳制到盒子范围内，得到盒子里离球心最近的点q
    return dot(p - q, p - q) <= radius2;//// 计算球心p到最近点q的距离平方，和半径平方比对
}

float udf2Triangle(float3 a, float3 b, float3 c, float3 p)
{
    float3 ba = b - a;
    float3 pa = p - a;
    float3 cb = c - b;
    float3 pb = p - b;
    float3 ac = a - c;
    float3 pc = p - c;
    float3 nor = cross(ba, ac);

    if (sign(dot(cross(ba, nor), pa)) +
        sign(dot(cross(cb, nor), pb)) +
        sign(dot(cross(ac, nor), pc)) < 2)
    {
        return min(
            min(
                dot2(ba * clamp(dot(ba, pa) / dot2(ba), 0.0, 1.0) - pa),
                dot2(cb * clamp(dot(cb, pb) / dot2(cb), 0.0, 1.0) - pb)
            ),
            dot2(ac * clamp(dot(ac, pc) / dot2(ac), 0.0, 1.0) - pc)
        );
    }

    return dot(nor, pa) * dot(nor, pa) / dot2(nor);
}
/// 三角形和球体相交检测
bool intersectSphereTriangle(float3 a, float3 b, float3 c, float3 o, float r2)
{
    return udf2Triangle(a, b, c, o) <= r2;
}

bool closestIntersectionWithTriangle(
    float3 o,
    float3 d,
    float maxT,
    float3 A,
    float3 B_A,
    float3 C_A,
    out float r_t)
{
    r_t = 0.0;

    float3 s1 = cross(d, C_A);
    float div = dot(s1, B_A);

    if (abs(div) < 1e-8)
        return false;

    float invDiv = 1.0 / div;

    float3 o_A = o - A;
    float alpha = dot(o_A, s1) * invDiv;

    float3 s2 = cross(o_A, B_A);
    float beta = dot(d, s2) * invDiv;

    float t = dot(C_A, s2) * invDiv;

    if (t < 0.0 || t > maxT || alpha < 0.0 || beta < 0.0 || alpha + beta > 1.0)
        return false;

    r_t = t;
    return true;
}

float max4(float x, float y, float z, float w)
{
    return max(max(x, y), max(z, w));
}

float min4(float x, float y, float z, float w)
{
    return min(min(x, y), min(z, w));
}

bool intersectRayBox(float3 o, float3 invD, float t0, float t1, float3 lower, float3 upper)
{
    float3 n = invD * (lower - o);
    float3 f = invD * (upper - o);

    float3 minnf = min(n, f);
    float3 maxnf = max(n, f);

    t0 = max4(t0, minnf.x, minnf.y, minnf.z);
    t1 = min4(t1, maxnf.x, maxnf.y, maxnf.z);

    return t0 <= t1;
}

//判断指定球体范围内，是否包含 / 相交 BVH 加速结构里的任意三角形
bool containsTriangle(float3 o, float radius2, uint nodeIndex)
{
    uint stack[BVH_STACK_SIZE];
    stack[0] = nodeIndex;
    int stackTop = 1;

    while (stackTop > 0)
    {
        uint ni = stack[--stackTop];
        Node node = Nodes[ni];
        //计算球体和 AABB 是否相交
        if (!intersectSphereBox(
            float3(node.minX, node.minY, node.minZ),
            float3(node.maxX, node.maxY, node.maxZ),
            o,
            radius2))
        {
            continue;
        }

        if (isLeaf(node))
        {
            // 叶子节点：存真实三角形
            for (uint i = 0, j = 3 * node.childIndex; i < node.childCount; ++i, j += 3)
            {
                /// 三角形和球体相交检测
                if (intersectSphereTriangle(
                    Vertices[j],
                    Vertices[j + 1],
                    Vertices[j + 2],
                    o,
                    radius2))
                {
                    return true;// 找到相交三角，直接返回存在
                }
            }
        }

        if (stackTop + 2 < BVH_STACK_SIZE)
        {
            stack[stackTop++] = node.childIndex;
            stack[stackTop++] = node.childIndex + 1;
        }
    }

    return false;
}

//给点 p 找一个“肯定够用的距离上限 upperBound”
float estimateUpperBound(float3 p, int precision)
{
    Node root = Nodes[0];
    float3 lower = float3(root.minX, root.minY, root.minZ);
    float3 upper = float3(root.maxX, root.maxY, root.maxZ);

    float L = 0.0;
    //distance(0.5 * (lower + upper), p) = 包围盒中心点和P点的距离   
    //R = 点 p 到模型中心距离 + 模型包围盒对角线长度
    float R = distance(0.5 * (lower + upper), p) + distance(lower, upper);

    for (int i = 0; i < precision; ++i)
    {
        float mid = 0.5 * (L + R);

        //判断指定球体范围内是否包含三角形
        if (containsTriangle(p, mid * mid, 0))
            R = mid;
        else
            L = mid;
    }

    return R;
}

int traceTriangleIndex(float3 o, float3 d, float maxT)
{
    float3 invD = 1.0 / d;

    uint stack[BVH_STACK_SIZE];
    stack[0] = 0;
    int stackTop = 1;

    int finalIdx = -1;
    float finalT = maxT;

    while (stackTop > 0)
    {
        uint ni = stack[--stackTop];
        Node node = Nodes[ni];

        if (!intersectRayBox(
            o,
            invD,
            0.0,
            finalT,
            float3(node.minX, node.minY, node.minZ),
            float3(node.maxX, node.maxY, node.maxZ)))
        {
            continue;
        }

        if (isLeaf(node))
        {
            for (uint i = 0, j = 3 * node.childIndex; i < node.childCount; ++i, j += 3)
            {
                float3 a = Vertices[j];
                float3 b = Vertices[j + 1];
                float3 c = Vertices[j + 2];

                float newT;
                if (closestIntersectionWithTriangle(o, d, finalT, a, b - a, c - a, newT))
                {
                    finalT = newT;
                    finalIdx = int(i + node.childIndex);
                }
            }
        }
        else
        {
            if (stackTop + 2 < BVH_STACK_SIZE)
            {
                stack[stackTop++] = node.childIndex;
                stack[stackTop++] = node.childIndex + 1;
            }
        }
    }

    return finalIdx;
}

struct UDF2Result
{
    int triIdx;
    float udf2;
};

int estimateSign(float3 o, float rn)
{
    int rndTriIdx = int(rn * max(0, TriangleCount - 1));

    float3 a = Vertices[rndTriIdx * 3 + 0];
    float3 b = Vertices[rndTriIdx * 3 + 1];
    float3 c = Vertices[rndTriIdx * 3 + 2];

    float3 d = (a + b + c) / 3.0 - o;

    int triIdx = traceTriangleIndex(o, d, 3.402823e+38);

    if (triIdx < 0)
        return 0;

    float3 na = Normals[triIdx * 3 + 0];
    float3 nb = Normals[triIdx * 3 + 1];
    float3 nc = Normals[triIdx * 3 + 2];

    return dot(d, na + nb + nc) < 0.0 ? 1 : -1;
}

UDF2Result udf2(float3 p, float u2, uint nodeIndex)
{
    uint stack[BVH_STACK_SIZE];
    stack[0] = nodeIndex;
    int stackTop = 1;

    int finalTriIdx = -1;

    while (stackTop > 0)
    {
        uint ni = stack[--stackTop];
        Node node = Nodes[ni];

        if (!intersectSphereBox(
            float3(node.minX, node.minY, node.minZ),
            float3(node.maxX, node.maxY, node.maxZ),
            p,
            u2))
        {
            continue;
        }

        if (isLeaf(node))
        {
            for (uint i = 0, j = 3 * node.childIndex; i < node.childCount; ++i, j += 3)
            {
                float newUDF2 = udf2Triangle(
                    Vertices[j],
                    Vertices[j + 1],
                    Vertices[j + 2],
                    p);

                if (newUDF2 < u2)
                {
                    u2 = newUDF2;
                    finalTriIdx = int(i + node.childIndex);
                }
            }
        }
        else
        {
            if (stackTop + 2 < BVH_STACK_SIZE)
            {
                stack[stackTop++] = node.childIndex;
                stack[stackTop++] = node.childIndex + 1;
            }
        }
    }

    UDF2Result result;
    result.triIdx = finalTriIdx;
    result.udf2 = u2;

    return result;
}
//方法作用  输入一个空间点p 输出这个点到模型表面的 signed distance   外部：正数  表面：接近 0  内部：负数
float sdf(float3 p, float upperBound)
{
    if (upperBound <= 0.0)
        upperBound = estimateUpperBound(p, 6);

    UDF2Result result = udf2(p, upperBound * upperBound, 0);

    float udfVal = sqrt(result.udf2);
    int triIdx = result.triIdx;

    if (triIdx < 0)
        return udfVal;

    int signEstimator = 0;

    for (int i = 0; i < SignRayCount; ++i)
    {
        signEstimator += estimateSign(
            p,
            lerp(0.0, 1.0, (i + 0.5) / SignRayCount));
    }

    if (signEstimator > 0)
        return udfVal;

    if (signEstimator < 0)
        return -udfVal;

    float3 a = Vertices[triIdx * 3 + 0];
    float3 b = Vertices[triIdx * 3 + 1];
    float3 c = Vertices[triIdx * 3 + 2];

    float3 na = Normals[triIdx * 3 + 0];
    float3 nb = Normals[triIdx * 3 + 1];
    float3 nc = Normals[triIdx * 3 + 2];

    int ja = dot(p - a, na) >= 0.0 ? 1 : -1;
    int jb = dot(p - b, nb) >= 0.0 ? 1 : -1;
    int jc = dot(p - c, nc) >= 0.0 ? 1 : -1;

    return ja + jb + jc > 0 ? udfVal : -udfVal;
}

[numthreads(1, GROUP_SIZE, GROUP_SIZE)]
void CSMain(uint3 threadIdx : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;

    SDF.GetDimensions(width, height, depth);//获取tex3D的 像素宽深高

    if (threadIdx.y >= height || threadIdx.z >= depth)
        return;

    float dx = 1.05 * SDFExtent.x / width;//放大 5% 余量，防止采样边界卡缝隙、漏采样、精度截断出黑边 / 断层

    float zf = lerp(SDFLower.z, SDFUpper.z, (threadIdx.z + 0.5) / depth);//获取当前像素的z的局部坐标
    float yf = lerp(SDFLower.y, SDFUpper.y, (threadIdx.y + 0.5) / height);//获取当前像素的y的局部坐标

    float lastUDF = -100.0 * dx; // 初始化上一格的无符号距离 lastUDF，让第一轮循环不要使用它作为有效搜索半径。

    for (int x = XBeg; x < XEnd; ++x)//0 => resolution
    {
        float xf = lerp(SDFLower.x, SDFUpper.x, (x + 0.5) / width);
        float upperBound = lastUDF + dx;

        float newSDF = sdf(float3(xf, yf, zf), upperBound);//获取当前像素的sdf
        lastUDF = abs(newSDF);

        SDF[uint3(x, threadIdx.y, threadIdx.z)] = newSDF;
    }
}
