// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMainT

#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"
// RWTexture2D<float4> Result;
StructuredBuffer<float4> _voxelPositions;
StructuredBuffer<float4> _voxelNormals;
RWBuffer<float4> _voxelColors;
[numthreads(1,1,1)]
void CSMainT (uint3 id : SV_DispatchThreadID)
{
    
//main light
    float3 L = normalize(_MainLightPosition);
    float3 N = normalize(_voxelNormals[id.x]);
    float3 worldPos = _voxelPositions[id.x];
    half3 diffuse = saturate(dot(N,L));
// ambient
    float3 ambinet = SampleSH(N);    
    diffuse += ambinet*0.5;
    
//add light
    uint lightsCount = GetAdditionalLightsCount();
    uint meshRenderingLayers = GetMeshRenderingLayer();

    LIGHT_LOOP_BEGIN(lightsCount)
        Light light = GetAdditionalLight(lightIndex, worldPos);

    // #ifdef _LIGHT_LAYERS
    // if (IsMatchingLightLayer(light.layerMask, meshRenderingLayers))
    //     #endif
    // {
        half3 lightColor = light.color * light.distanceAttenuation;
        diffuse += LightingLambert(lightColor, light.direction, N);
    // }
    
    LIGHT_LOOP_END
    _voxelColors[id.x] = float4(diffuse,1);
    
}
