// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMainT

#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"
// RWTexture2D<float4> Result;
StructuredBuffer<float4> _voxelPositions;
StructuredBuffer<float4> _voxelNormals;
StructuredBuffer<int> _voxelAtten;
StructuredBuffer<float4> _MainColor;
RWBuffer<float4> _voxelColors;
[numthreads(1024,1,1)]
void CSMainT (uint3 id : SV_DispatchThreadID)
{
    
// main light
     float3 L = normalize(_MainLightPosition);
     float3 N = normalize(_voxelNormals[id.x]);
     float3 worldPos = _voxelPositions[id.x];
     half3 diffuse = saturate(dot(N,L))*_voxelAtten[id.x]*_MainColor[id.x];
    
 // ambient
     float3 ambinet = pow(SampleSH(N),1/2.2f);    
     diffuse += ambinet*_MainColor[id.x];
 //add light
     uint lightsCount = GetAdditionalLightsCount();
     uint meshRenderingLayers = GetMeshRenderingLayer();

     LIGHT_LOOP_BEGIN(lightsCount)
         Light light = GetAdditionalLight(lightIndex, worldPos);
         half3 lightColor = light.color * light.distanceAttenuation;
         diffuse += LightingLambert(lightColor, light.direction, N);
     
     LIGHT_LOOP_END
     // diffuse-=1;
    _voxelColors[id.x] = float4(diffuse,1);
    
}
